spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  flyway:
    baselineOnMigrate: true

  mvc.view.prefix: /WEB-INF/jsp/
  mvc.view.suffix: .jsp


server:
  port: 8090

bezkoder.app.jwtSecret: ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs: 86400000
